### ISSUE TITLE
mje new issue kholny ka dil chaha patri sbz

### ISSUE THREAD

**Issue by sanwalchaudhry** [adam-pk/Rainbow-Poem#10]
bethy bethy raat ko issue kholny ka dil a gya aur phir pull kr k isko set krna hy IA ...
[This is the link] (http://au.edu.pk)
![Scene](https://user-images.githubusercontent.com/7696772/58360598-f8205a80-7e89-11e9-8080-30a272807bd2.jpg)

**Comment by adam-pk** [comment]
fazol sa tha yh. ab bnd kro isko
